//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\dsi-cad48x\c$\TEMP\DSIRevitToolkit.
        /// </summary>
        internal static string DEBUG_EXECUTABLE_PATH {
            get {
                return ResourceManager.GetString("DEBUG_EXECUTABLE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Release.
        /// </summary>
        internal static string DEBUG_PATH_POSTFIX {
            get {
                return ResourceManager.GetString("DEBUG_PATH_POSTFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\hisler\source\repos\dsi-toolkit\src\bin\.
        /// </summary>
        internal static string DEBUG_PATH_PREFIX {
            get {
                return ResourceManager.GetString("DEBUG_PATH_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSIRevitToolkit.
        /// </summary>
        internal static string DLL_NAME {
            get {
                return ResourceManager.GetString("DLL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ca60eee-f672-47f5-bb60-8764fa0bfe33.
        /// </summary>
        internal static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsi-revit-toolkit.
        /// </summary>
        internal static string INSTALL_DIRECTORY_NAME {
            get {
                return ResourceManager.GetString("INSTALL_DIRECTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\budacad\cad\Revit\DSIRevitToolkit.
        /// </summary>
        internal static string REMOTE_EXECUTABLE_PATH {
            get {
                return ResourceManager.GetString("REMOTE_EXECUTABLE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ProgramData\Autodesk\Revit\Addins.
        /// </summary>
        internal static string REVIT_ADDINS_PATH {
            get {
                return ResourceManager.GetString("REVIT_ADDINS_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\budacad\cad\Revit\DSIRevitToolkit\.
        /// </summary>
        internal static string SOURCE_PATH_PREFIX {
            get {
                return ResourceManager.GetString("SOURCE_PATH_PREFIX", resourceCulture);
            }
        }
    }
}
